# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-10 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=6)),
                ('stu_sex', models.BooleanField(default=0)),
                ('stu_num', models.CharField(max_length=10, unique=True)),
                ('stu_delete', models.BooleanField(default=0)),
                ('stu_create_time', models.DateField(auto_now_add=True)),
                ('stu_operate_time', models.DateField(auto_now=True)),
                ('stu_Chinese', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('stu_Math', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('stu_English', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('stu_Physics', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('stu_Chemistry', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('stu_Organism', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
            ],
        ),
    ]
