# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-15 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_auto_20180514_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stu_delete',
        ),
        migrations.AddField(
            model_name='student',
            name='i_image',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
    ]
