# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0004_auto_20180523_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stu_Chemistry',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_English',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_Math',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_Organism',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stu_Physics',
        ),
        migrations.AlterModelTable(
            name='student',
            table='stu_student',
        ),
    ]
