# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0005_auto_20180524_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stu_Chinese',
            new_name='stu_grade',
        ),
    ]
