# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-24 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0006_auto_20180524_2138'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentinfo',
            table='stu_studentinfo',
        ),
    ]
