# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0007_auto_20180524_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='s',
        ),
        migrations.AddField(
            model_name='student',
            name='i_image',
            field=models.ImageField(null=True, upload_to='upload'),
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
