# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0010_remove_student_stu_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=6, unique=True)),
                ('s_num', models.CharField(max_length=10, unique=True)),
                ('s_class', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'db_table': 'stu_class',
            },
        ),
    ]
