# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0013_auto_20180603_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_num', models.CharField(max_length=10, unique=True)),
                ('s_name', models.CharField(max_length=6)),
                ('s_grade', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
            ],
        ),
    ]
