# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0014_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='s_grade',
            new_name='s_Chinese',
        ),
        migrations.AddField(
            model_name='grade',
            name='s_English',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='grade',
            name='s_Math',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
