# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0015_auto_20180603_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='s_Chinese',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='grade',
            name='s_English',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='grade',
            name='s_Math',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
    ]
