# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-18 01:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0017_auto_20180603_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='s_name',
            field=models.CharField(max_length=6),
        ),
    ]
